security:
    providers:
        in_memory:
            memory:
                users:
                    guest:
                        password: wamguest
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: ~

    access_control:
        - { path: ^/, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
